import hashlib
import json
import time
from ecdsa import SigningKey, NIST256p

class SGXAttestationMock:
    """
    Mock class to simulate Intel SGX Remote Attestation.
    In a real SGX environment, this would call the DCAP library.
    """
    def __init__(self):
        # Generate a distinct key pair for the Enclave
        self._enclave_sk = SigningKey.generate(curve=NIST256p)
        self.enclave_pk = self._enclave_sk.verifying_key
        # Simulate MRENCLAVE (Measurement of the code)
        self.mrenclave = "0x7f3c...simulated_hash_of_inference_code"

    def generate_quote(self, verdict_json):
        """
        Signs the verdict to prove it was generated by this specific Enclave.
        """
        payload = json.dumps(verdict_json, sort_keys=True).encode()
        
        # 1. Create a hash of the execution result (User Data Report)
        report_data = hashlib.sha256(payload).hexdigest()
        
        # 2. Sign the report data (Simulating the Quoting Enclave)
        signature = self._enclave_sk.sign(payload)
        
        # 3. Construct the Quote structure
        quote = {
            "mrenclave": self.mrenclave,
            "report_data": report_data,
            "signature": signature.hex(),
            "timestamp": time.time(),
            "tee_platform": "SGX_SIM_MODE"
        }
        return quote

    def get_public_key_hex(self):
        return self.enclave_pk.to_string().hex()